import unittest

from text2sql.api.errors import build_error


class ApiErrorsTest(unittest.TestCase):
    def test_structured_error_body_has_required_fields(self):
        body = build_error("internal_error", "boom").to_dict()
        self.assertEqual(set(body), {"code", "message", "trace_id"})
        self.assertEqual(body["code"], "internal_error")
        self.assertEqual(body["message"], "boom")
        self.assertTrue(body["trace_id"])

    def test_trace_id_autogenerated_and_unique(self):
        first = build_error("internal_error", "boom")
        second = build_error("internal_error", "boom")
        self.assertNotEqual(first.trace_id, second.trace_id)


if __name__ == "__main__":
    unittest.main()
