"""create core metadata tables

Revision ID: 361a4f441bbe
Revises: 
Create Date: 2026-06-28 18:08:18.385146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361a4f441bbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_run_at'), 'eval_runs', ['run_at'], unique=False)
    op.create_table('few_shot_examples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.Column('chart_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schema_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=128), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=True),
    sa.Column('alias', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enum_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_metadata_table_name'), 'schema_metadata', ['table_name'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('query_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('rewritten_query', sa.Text(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('tables', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('chart_type', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('elapsed_ms', sa.Float(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('render_spec', sa.JSON(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_created_at'), 'query_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_query_history_session_id'), 'query_history', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_session_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_created_at'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_schema_metadata_table_name'), table_name='schema_metadata')
    op.drop_table('schema_metadata')
    op.drop_table('few_shot_examples')
    op.drop_index(op.f('ix_eval_runs_run_at'), table_name='eval_runs')
    op.drop_table('eval_runs')
    # ### end Alembic commands ###
